export function editorialPages({ data, esc, tag, link, externalLink, picture, intro, formatDate }) {
  const sources = new Map(data.sources.map((source) => [source.id, source]));
  const sourceLink = (id, label = "Consultar fonte") => {
    const source = sources.get(id);
    return source?.originUrl ? externalLink(source.originUrl, label) : "";
  };
  const founder = data.idealizador;

  const idealizador = `<section class="founder-hero"><div class="container">
    <nav class="breadcrumb" aria-label="Caminho da página"><a href="/">Início</a><span aria-hidden="true">/</span><span>Idealizador</span></nav>
    <div class="founder-hero-grid"><div><p class="eyebrow">IDEALIZADOR</p><h1>${esc(founder.name)}</h1><p class="founder-role">${esc(founder.role)}</p><p class="founder-description">${esc(founder.description)}</p><a class="text-link" href="#trajetoria">Conheça a trajetória <span aria-hidden="true">↓</span></a></div>
    <figure class="founder-portrait"><img src="/assets/img/idealizador/antonio-mateus.webp" alt="Antônio Mateus de Carvalho Soares em atividade pública" width="320" height="318" fetchpriority="high" decoding="async"><figcaption>Antônio Mateus de Carvalho Soares</figcaption></figure></div>
    <div class="founder-triad" aria-label="Eixos centrais: Violência, Educação e Direitos Humanos"><span>Violência</span><span>Educação</span><span>Direitos Humanos</span></div>
  </div></section>
  <nav class="editorial-index container" aria-label="Nesta página"><a href="#trajetoria">Trajetória <span aria-hidden="true">↓</span></a><a href="#pesquisa">Pesquisa e atuação <span aria-hidden="true">↓</span></a><a href="#formacao">Formação <span aria-hidden="true">↓</span></a><a href="#producao">Produção acadêmica <span aria-hidden="true">↓</span></a><a href="#midia">Voz pública <span aria-hidden="true">↓</span></a></nav>
  <section class="section" id="trajetoria"><div class="container editorial-split"><div><p class="eyebrow">Trajetória</p><h2>Pesquisa, docência<br>e debate público</h2></div><div class="editorial-prose"><p class="lead">Antônio Mateus atua na Universidade e em espaços públicos de formação e debate, aproximando pesquisa social de questões presentes no cotidiano.</p><p>Na UFRB, sua atuação em Ciências Sociais e a relação com o Observatório Social da Juventude dialogam com temas que atravessam o próprio ELO: juventudes, escola, território, comunicação e direitos.</p><div class="related-links">${sourceLink("ufrb-docentes-ciso", "Docência na UFRB")}${sourceLink("ufrb-osj", "Observatório Social da Juventude")}</div></div></div></section>
  <section class="section founder-research" id="pesquisa"><div class="container"><div class="editorial-heading"><p class="eyebrow">Pesquisa e atuação</p><h2>Três eixos.<br>Questões em comum.</h2></div><div class="research-axes">${founder.axes.map((axis, index) => `<article><span class="axis-number">0${index + 1}</span><h3>${esc(axis.title)}</h3><p>${esc(axis.text)}</p></article>`).join("")}</div></div></section>
  <section class="section founder-formation" id="formacao"><div class="container editorial-split"><div><p class="eyebrow">Formação e pesquisa</p><h2>Percursos que<br>se encontram</h2></div><ol class="founder-timeline">${founder.milestones.map((item) => `<li><span class="timeline-year">${esc(item.year)}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p>${sourceLink(item.sourceId)}</div></li>`).join("")}</ol></div></section>
  <section class="section" id="producao"><div class="container"><div class="editorial-heading"><p class="eyebrow">Produção acadêmica</p><h2>Leituras selecionadas</h2></div><p class="editorial-deck">Uma seleção curta para apresentar caminhos da pesquisa sem transformar esta página em um currículo completo.</p><div class="selected-works">${founder.works.map((work, index) => `<article><span class="work-number">0${index + 1}</span><div><p class="eyebrow">${esc(work.meta)}</p><h3>${esc(work.title)}</h3><p class="work-credit">${esc(work.credit)}</p>${sourceLink(work.sourceId, "Consultar publicação")}</div></article>`).join("")}</div></div></section>
  <section class="section founder-media" id="midia"><div class="container"><div class="editorial-heading"><p class="eyebrow">Voz pública</p><h2>Entrevistas e debates</h2></div><div class="media-grid">${data.media.filter((item) => item.scope === "idealizador").map((item) => item.provider === "youtube" ? `<article class="media-entry"><div class="media-player" data-video="${esc(item.videoId)}" data-video-title="${esc(item.title)}"><div class="media-placeholder"><span aria-hidden="true">▶</span><strong>${esc(item.title)}</strong><small>${esc(item.vehicle)} · ${esc(item.year)}</small></div><button type="button" class="video-load">Assistir aqui</button></div><div class="media-copy"><p class="eyebrow">${esc(item.vehicle)} · ${esc(item.year)}</p><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p>${externalLink(item.url, "Consultar a fonte")}</div></article>` : `<article class="media-entry media-external"><div class="media-placeholder media-tv"><span>TV</span><strong>${esc(item.vehicle)}</strong><small>${esc(item.year)}</small></div><div class="media-copy"><p class="eyebrow">${esc(item.vehicle)} · ${esc(item.year)}</p><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p>${externalLink(item.url, "Assistir no Globoplay")}</div></article>`).join("")}</div></div></section>
  <section class="section founder-elo"><div class="container editorial-split"><div><p class="eyebrow">Universidade em rede</p><h2>O ELO nessa trajetória</h2></div><div class="editorial-prose"><p class="lead">No ELO, pesquisa, extensão e comunicação se encontram em uma proposta de circulação de conhecimentos entre Universidade, Comunidade e Território.</p><p>A trajetória do idealizador ajuda a contextualizar temas que aparecem nas ações e publicações do projeto, sem confundir a produção pessoal do pesquisador com o arquivo institucional do ELO.</p><div class="related-links">${link("/sobre/", "Conheça o projeto")}${link("/acoes/", "Explore as ações")}</div></div></div></section>
  <section class="section founder-profiles"><div class="container"><div class="editorial-heading"><p class="eyebrow">Referências</p><h2>Perfis acadêmicos e públicos</h2></div><div class="profile-links">${founder.profiles.map((profile) => sourceLink(profile.sourceId, profile.label)).join("")}</div></div></section>`;

  const posts = [...data.publicationArchive].sort((a, b) => (b.date || "").localeCompare(a.date || ""));
  const publicationItem = (item, featured = false) => `<article class="publication-record${featured ? " publication-feature" : ""}">${item.image ? `<a class="publication-record-image" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer">${picture(item, { eager: featured })}</a>` : `<div class="publication-record-mark" aria-hidden="true"><span>ELO.UFRB</span><b>${esc(item.type)}</b></div>`}<div><p class="eyebrow">${esc(item.type)}</p>${item.date ? `<time datetime="${esc(item.date)}">${esc(formatDate(item.date))}</time>` : ""}<h${featured ? "2" : "3"}>${esc(item.title)}</h${featured ? "2" : "3"}><p>${esc(item.description)}</p><div class="related-links">${externalLink(item.url, "Ver publicação no Instagram", "Instagram")}${item.relatedUrl ? link(item.relatedUrl, item.relatedLabel || "Saiba mais") : ""}</div></div></article>`;
  const publicacao = `${intro("Publicação", "Publicações do ELO.UFRB", "Registros, chamadas, documentos e conteúdos que colocam o projeto em circulação.")}<section class="section publication-highlight"><div class="container"><div class="editorial-heading"><p class="eyebrow">Em destaque</p><h2>O que está circulando agora</h2></div>${posts[0] ? publicationItem(posts[0], true) : ""}</div></section><section class="section"><div class="container"><div class="editorial-heading"><p class="eyebrow">Arquivo editorial</p><h2>Publicações recentes</h2></div><div class="publication-records">${posts.slice(1).map((item) => publicationItem(item)).join("")}</div></div></section><section class="section publication-documents"><div class="container editorial-split"><div><p class="eyebrow">Documentos e materiais</p><h2>Projeto institucional</h2><p>O documento de renovação reúne objetivos, fundamentos e metodologia do ELO.UFRB para 2025 a 2027.</p></div><div>${data.publications.map((item) => `<article class="document-row"><span>${esc(item.type)}</span><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><a class="text-link" href="${esc(encodeURI(item.url))}" download>Baixar documento <span aria-hidden="true">→</span></a></article>`).join("")}</div></div></section>`;

  const relation = (item) => `<article class="partner-row"><div><p class="eyebrow">${esc(item.context || item.shortName || "")}</p><h3>${esc(item.name)}</h3></div><div><p>${esc(item.text)}</p><div class="related-links">${item.actionUrl ? link(item.actionUrl, "Conheça a atividade") : ""}${sourceLink(item.sourceId, "Consultar fonte")}</div></div></article>`;
  const parceira = `${intro("Parceira", "Relações que fazem o ELO", "Parcerias confirmadas, vínculos institucionais e interlocuções construídas nas atividades do projeto.")}<section class="section"><div class="container"><div class="editorial-heading"><p class="eyebrow">Base institucional</p><h2>Universidade e projeto</h2></div><div class="partner-list">${data.partners.institutional.map(relation).join("")}</div></div></section><section class="section partner-confirmed"><div class="container"><div class="editorial-heading"><p class="eyebrow">Parcerias documentadas</p><h2>Construções em conjunto</h2></div><div class="partner-list">${data.partners.confirmed.map(relation).join("")}</div></div></section><section class="section"><div class="container"><div class="editorial-heading"><p class="eyebrow">Redes e interlocuções</p><h2>Encontros que ampliam a rede</h2><p class="editorial-deck">Participar de uma atividade não significa parceria institucional permanente. Esta seção registra relações documentadas em contextos específicos.</p></div><div class="partner-list">${data.partners.networks.map(relation).join("")}</div></div></section>`;

  const homeFounder = `<section class="section home-founder"><div class="container home-founder-grid"><figure><img src="/assets/img/idealizador/antonio-mateus.webp" alt="Antônio Mateus de Carvalho Soares" width="320" height="318" loading="lazy" decoding="async"></figure><div><p class="eyebrow">Idealizador</p><h2>Antônio Mateus<br>de Carvalho Soares</h2><p class="home-founder-axis">Violência · Educação · Direitos Humanos</p><p>Professor e pesquisador da UFRB. Sua trajetória em Ciências Sociais ajuda a contextualizar os debates que atravessam o projeto.</p>${link("/idealizador/", "Conheça o idealizador")}</div></div></section>`;

  return { idealizador, publicacao, parceira, homeFounder };
}
